### PR TITLE
Fix misspellings

### PR DESCRIPTION
**Pull request by rtrv**
This fixes:
- Some misspellings and errors
- Quotes in Ruby code examples to fit the style guide

### CODE REVIEW

**Comment by palkan** [comment]
Thanks!

In order to support code style in guides we have to add some automation, kind of markdown code blocks linter (RuboCop in our case). Otherwise it would be hardly possible to provide code style consistency.

Let's revert this part of the PR and think about how to implement this.

**Comment by rtrv** [comment]
Ok, I'll revert it. If you create an issue of markdown RuboCop linting, I would pick it

**Comment by rtrv** [comment]
Done and rebased

**Comment by palkan** [comment]
@rtrv FYI #53

**Comment by rtrv** [comment]
@palkan thanks, the thing!

**Pull request merged**
