### PR TITLE
Fix documentation link

### PR DESCRIPTION
**Pull request by sallesma**
Just a typo or a link that has moved :)

### CODE REVIEW

**Comment by sallesma** [comment]
Not sure to understand how this change can break the build. Was it already broken?

**Comment by palkan** [comment]
@pirj Could you please take a look? Probably, new RuboCop release broke something with AggregateFailures cop.

**Comment by pirj** [comment]
@sallesma Upstream changes ¯\\\_(ツ)_/¯
Fixed in https://github.com/palkan/test-prof/pull/191

**Comment by pirj** [comment]
Thanks for the fix @sallesma !

**Comment by sallesma** [comment]
That was so much work! 😉 

Thanks for the repo, my life is about to get better

**Pull request merged**
